// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9e9ug42BNZPvAqkrcSTgTHvYa-Csz5XI',
    appId: '1:863026714670:web:810ebf0f53401a2c4367bf',
    messagingSenderId: '863026714670',
    projectId: 'curren-see-d15bc',
    authDomain: 'curren-see-d15bc.firebaseapp.com',
    storageBucket: 'curren-see-d15bc.firebasestorage.app',
    measurementId: 'G-DKZ7MXY0GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDljFVgN230NVG8taPloqTfHiidABuQuDM',
    appId: '1:863026714670:android:fdc58071c45b140c4367bf',
    messagingSenderId: '863026714670',
    projectId: 'curren-see-d15bc',
    storageBucket: 'curren-see-d15bc.firebasestorage.app',
  );

}